/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_syntaxerror_cpuid4j_CPUID */

#ifndef _Included_at_syntaxerror_cpuid4j_CPUID
#define _Included_at_syntaxerror_cpuid4j_CPUID
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     at_syntaxerror_cpuid4j_CPUID
 * Method:    cpuid2
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_at_syntaxerror_syntaxc_backend_x86_CPUID_cpuid2(JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
